### ISSUE TITLE
How to nest subgraph db inside reframe's app_db

### ISSUE THREAD

**Issue by jhund** [vimsical/subgraph#15]
@julienfantin thank you for this fantastic library. I'm just getting started with it in my re-frame app. I have a certain structure for my re-frame app_db and would like to stick a subgraph db under the :subgraph key like so:

```clojure
(def default-db
  {
    :ui { ... }
    :subgraph (-> (subgraph/new-db)
                  (subgraph/add-id-attr
                    :user/name
                    :color/hex))
    :server { ... }
  }
)
```

Is this possible? I managed writing to it with this event handler for `:add` using re-frame's `path` interceptor:

```clojure
(re-frame/reg-event-db
 :add-subgraph
 [(re-frame/path :subgraph)]
 (fn [db-sg [_ & entities]]
   (apply subgraph/add db-sg entities)))
```

However I'm having trouble with my subscriptions, and I can't pinpoint the cause. Here is my generic query subscription:

```clojure
(re-frame/reg-sub
 :sg-query
 (fn [db [pattern lookup-ref]]
   (subgraph.reframe/pull (db :subgraph) pattern lookup-ref)))
```
Do you think this should work?

Thank you for your help.

**Comment by julienfantin** [comment]
Hi @jhund,

I've always used the subgraph db as _the_ app-db, but yours is a valid use-case that should work.

Your event handler seems correct, but I see a couple of issues in the subscription:

1. You seem to have forgotten to ignore the first arg in the query vector, so I assume your `pattern` is actually bound to `:sg-query` here.
2. That `vimsical.subgraph.reframe/pull` function was meant to work with the whole db as a ratom, inside a `reg-sub-raw`.  In this case you should use `vimsical.subgraph/pull` instead.

**Comment by jhund** [comment]
@julienfantin thank you very much for your tips. They helped, it's now working. I'd like to check one more thing with you: `subgraph/pull` returns a reaction. So my `:sg-query` subscription returns a reaction:

```clojure
(re-frame/reg-sub
 :sg-query
 (fn [db [_ pattern lookup-ref]]
   (subgraph/pull (db :subgraph) pattern lookup-ref)))
```

I then have another subscription that gets a particular entity out of the subgraph db. And this is where I'm getting confused. Why do I have to deref the return value from the `:sg-query` subscription?:

```clojure
(re-frame/reg-sub
  :testing/user
  (fn [db _]
    @(re-frame/subscribe  ; <== This deref is what I don't fully understand
      [:sg-query
        [:user/id :user/name]
        [:user/id 1]])))
```

And then I use the subscription in my view:

```clojure
(defn user-details
  []
  (let [user @(re-frame/subscribe [:testing/user])]
    [:div
      [:ul
        [:li (str "Name: " (user :user/name))]
        [:li (str "ID: " (user :user/id))]]]))
```

With the double deref it works as expected. When I update my app db, the view updates automatically with new attributes for user 1.

What confuses me is that I have to deref the return value of `:sg-query` in `:testing/user`. When I look at re-frame examples for cascading subscriptions, the higher level subscriptions don't deref return values from lower level ones.

Can you please help me understand?

Thanks again for this fantastic library.

**Comment by julienfantin** [comment]
```clojure
(re-frame/reg-sub
 :sg-query
 (fn [db [_ pattern lookup-ref]]
   (subgraph/pull (db :subgraph) pattern lookup-ref)))
```

In that handler `db` is a map, `(db :subgraph)` is also a map and `subgraph/pull` will return a map as well, _not a reaction_. This is intended because the contract for `reg-sub` is to return a value. Re-frame is in charge of creating the reaction and will internally use that returned value to update the reaction it creates for your when you `(subcribe [:sg-query ...])`.

```clojure
(re-frame/reg-sub
  :testing/user
  (fn [db _]
    @(re-frame/subscribe  ; <== This deref is what I don't fully understand
      [:sg-query
        [:user/id :user/name]
        [:user/id 1]])))
```

Here is where `subscribe` returns a reaction, but again `reg-sub` expects you to return a normal value instead, that's why you have to deref it. 

In that case you should use `reg-sub-raw` which expects you to return a reaction:

```clojure
(re-frame/reg-sub-raw
  :testing/user
  (fn [_ _]
    (re-frame/subscribe
      [:sg-query
        [:user/id :user/name]
        [:user/id 1]])))
```

**Comment by jhund** [comment]
Thank you very much for your support. I had to chew a bit on what you said. Now I get it. Below is an alternative approach for handling the difference between a reaction and a value. This approach helped me reconcile what I see in the re-frame documentation/example where dependent subscriptions don't deref their input subscriptions. I was missing the optional input signal function:

```clojure
(re-frame/reg-sub
  :testing/user
  ; input signals fn
  (fn [query-v]
    (re-frame/subscribe
      [:sg-query
        [:user/id :user/name]
        [:user/id 1]]))
  ; computation fn
  (fn [sg-query query-v]
    sg-query))
```

**Comment by julienfantin** [comment]
Indeed that's also a correct way to do this 👍
