### ISSUE TITLE
readme edits

### ISSUE THREAD

**Issue by den1k** [vimsical/subgraph#3]
### Clarifications
- [ ] make clear that subgraph is based on a fork of mapgraph
- [ ] explain the tradeoffs of decomplecting the component tree from the shape of the data - om.next

### Examples
- [ ] interactive tutorial using re-frame and subgraph

**Comment by julienfantin** [comment]
What do you have in mind w.r.t. trade offs?

**Comment by den1k** [comment]
@julienfantin simply that their might be apps were the components mostly match the shape of the data. In such cases om.next might be sufficient. But for apps with many link (top-level) lookups, that each may have deep queries its less useful. So I suggest we state what kind of apps subgraph suits best.
